# DVC Pipeline Configuration
# Define your data processing stages here
# Each stage runs a command and tracks dependencies and outputs

# To run the pipeline: dvc repro
# To visualize: dvc dag

stages:
  # Stage 1: Convert raw data to intermediate format
  raw_to_intermediate:
    cmd: uv run python3 src/data_pipelines/raw_to_intermediate.py
    deps:
      - src/data_pipelines/raw_to_intermediate.py
      - data/raw/pc_price/pc_price_eu.csv
      - data/raw/pc_price/pc_price_asia.csv
      - data/raw/DEXCHUS.csv
      - data/raw/DEXINUS.csv
    outs:
      - data/intermediate/pc_price/intermediate_pc_price_eu.csv
      - data/intermediate/pc_price/intermediate_pc_price_asia.csv
