# DVC Pipeline Configuration
# Define your data processing stages here
# Each stage runs a command and tracks dependencies and outputs

# To run the pipeline: dvc repro
# To visualize: dvc dag

stages:
  # Stage 1: Convert raw data to intermediate format
  raw_to_intermediate:
    cmd: uv run python3 src/data_pipelines/raw_to_intermediate.py
    deps:
      - src/data_pipelines/raw_to_intermediate.py
      - data/raw/pc_price/pc_price_eu.csv
      - data/raw/pc_price/pc_price_asia.csv
      - data/raw/DEXCHUS.csv
      - data/raw/DEXINUS.csv
      - data/raw/phenol_acetone_capacity_loss/phenol_consumption_capacity_loss_kt.pq
      - data/raw/phenol_acetone_capacity_loss/acetone_consumption_capacity_loss_kt.pq
      - data/raw/electricity_price/european_wholesale_electricity_price_data_monthly.csv
      - data/raw/automobile_industry/ECB Data Portal_20251123141544.csv
      - data/raw/shutdown/Acetone.csv
      - data/raw/shutdown/Phenol.csv
    outs:
      - data/intermediate/pc_price/intermediate_pc_price_eu.csv
      - data/intermediate/pc_price/intermediate_pc_price_asia.csv
      - data/intermediate/pc_price/intermediate_pc_price_eu_grouped.csv
      - data/intermediate/pc_price/intermediate_pc_price_asia_grouped.csv
      - data/intermediate/phenol_acetone_capacity_loss/intermediate_bpa_capacity_loss.csv
      - data/intermediate/shutdown/intermediate_shutdown_capacity_loss.csv
      - data/intermediate/electricity_price/intermediate_european_wholesale_electricity_price.csv
      - data/intermediate/automobile_industry/intermediate_automobile_industry.csv


  # Stage 2: Convert intermediate data to processed format for univariate modeling
  intermediate_to_processed_uni:
    cmd: uv run python3 src/data_pipelines/uni_intermediate_to_processed.py
    deps:
      - src/data_pipelines/uni_intermediate_to_processed.py
      - data/intermediate/pc_price/intermediate_pc_price_eu.csv
      - data/intermediate/pc_price/intermediate_pc_price_asia.csv
      - data/intermediate/pc_price/intermediate_pc_price_eu_grouped.csv
      - data/intermediate/pc_price/intermediate_pc_price_asia_grouped.csv
      - data/intermediate/phenol_acetone_capacity_loss/intermediate_bpa_capacity_loss.csv
      - data/intermediate/electricity_price/intermediate_european_wholesale_electricity_price.csv
      - data/intermediate/automobile_industry/intermediate_automobile_industry.csv
      - data/intermediate/shutdown/intermediate_shutdown_capacity_loss.csv
      # TODO: Add other intermediate data dependencies as needed
    outs:
      - data/processed/uni_3m.csv
      - data/processed/uni_6m.csv
      - data/processed/uni_9m.csv
      - data/se_predictions/se_predictions_uni_grouped.csv
      - data/se_predictions/se_predictions_uni.csv

  # Stage 2 bis: Convert intermediate data to processed format for multivariate modeling
  intermediate_to_processed_multi:
    cmd: uv run python3 src/data_pipelines/multi_intermediate_to_processed.py
    deps:
      - src/data_pipelines/multi_intermediate_to_processed.py
      - data/intermediate/pc_price/intermediate_pc_price_eu.csv
      - data/intermediate/pc_price/intermediate_pc_price_asia.csv
      - data/intermediate/pc_price/intermediate_pc_price_eu_grouped.csv
      - data/intermediate/pc_price/intermediate_pc_price_asia_grouped.csv
      - data/intermediate/phenol_acetone_capacity_loss/intermediate_bpa_capacity_loss.csv
      - data/intermediate/electricity_price/intermediate_european_wholesale_electricity_price.csv
      - data/intermediate/automobile_industry/intermediate_automobile_industry.csv
      - data/intermediate/shutdown/intermediate_shutdown_capacity_loss.csv
      # TODO: Add other intermediate data dependencies as needed
    outs:
      - data/processed/multi_3m.csv
      - data/processed/multi_6m.csv
      - data/processed/multi_9m.csv
      - data/se_predictions/se_predictions_multi_grouped.csv
      - data/se_predictions/se_predictions_multi.csv
